service: lambda-environment

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,"qa"}
  environment:
    ${file(./config/env.${self:provider.stage}.json)}
  iamRoleStatements:
    ${file(./config/serverless/db.iam.yaml)}

functions:
  commit-message-scheduler:
    handler: handler.schedueler
    events: 
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: get commit messages each minute
          enabled: ${self:custom.enabled}
custom:
  schedulerRate: rate(1 minute) #tempo que o scheduler se repete
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  DbWriteCapacityUnitys: ${self:provider.environment.DbWriteCapacityUnitys}  
  DbReadCapacityUnitys: ${self:provider.environment.DbReadCapacityUnitys}

resources:
  Resources:
    ${file(./config/serverless/resources/dynamo.hero.table.yaml)}